import { appSchema, tableSchema } from '@nozbe/watermelondb';

export enum AddressType {
  BILLING = 'billing',
  SHIPPING = 'shipping',
  OTHER = 'other',
}

export default appSchema({
  version: 53,
  tables: [
    tableSchema({
      name: 'app_settings',
      columns: [
        { name: 'language', type: 'string' },
        { name: 'default_billing_interval', type: 'number', isOptional: true },
        { name: 'timer_soft_limit_enabled', type: 'boolean', isOptional: true },
        { name: 'timer_soft_limit_minutes', type: 'number', isOptional: true },
        { name: 'timer_hard_limit_enabled', type: 'boolean', isOptional: true },
        { name: 'timer_hard_limit_minutes', type: 'number', isOptional: true },
        { name: 'default_company_registry', type: 'string', isOptional: true },
        { name: 'is_vat_payer', type: 'boolean' },
        { name: 'invoice_company_name', type: 'string', isOptional: true },
        { name: 'invoice_address', type: 'string', isOptional: true },
        { name: 'invoice_street2', type: 'string', isOptional: true },
        { name: 'invoice_city', type: 'string', isOptional: true },
        { name: 'invoice_postal_code', type: 'string', isOptional: true },
        { name: 'invoice_country', type: 'string', isOptional: true },
        { name: 'invoice_company_id', type: 'string', isOptional: true },
        { name: 'invoice_vat_number', type: 'string', isOptional: true },
        { name: 'invoice_registration_note', type: 'string', isOptional: true },
        { name: 'invoice_email', type: 'string', isOptional: true },
        { name: 'invoice_phone', type: 'string', isOptional: true },
        { name: 'invoice_website', type: 'string', isOptional: true },
        { name: 'invoice_bank_account', type: 'string', isOptional: true },
        { name: 'invoice_iban', type: 'string', isOptional: true },
        { name: 'invoice_swift', type: 'string', isOptional: true },
        { name: 'invoice_logo_uri', type: 'string', isOptional: true },
        { name: 'default_invoice_currency', type: 'string', isOptional: true },
        { name: 'default_invoice_vat_code_id', type: 'string', isOptional: true },
        { name: 'default_invoice_payment_method', type: 'string', isOptional: true },
        { name: 'default_invoice_due_days', type: 'number', isOptional: true },
        { name: 'invoice_qr_type', type: 'string', isOptional: true },
        { name: 'invoice_default_export_format', type: 'string', isOptional: true },
        { name: 'invoice_series_prefix', type: 'string', isOptional: true },
        { name: 'invoice_series_pattern', type: 'string', isOptional: true },
        { name: 'invoice_series_next_number', type: 'number', isOptional: true },
        { name: 'invoice_series_padding', type: 'number', isOptional: true },
        { name: 'invoice_series_per_device', type: 'boolean', isOptional: true },
        { name: 'invoice_series_device_code', type: 'string', isOptional: true },
        { name: 'timesheet_series_prefix', type: 'string', isOptional: true },
        { name: 'timesheet_series_pattern', type: 'string', isOptional: true },
        { name: 'timesheet_series_next_number', type: 'number', isOptional: true },
        { name: 'timesheet_series_padding', type: 'number', isOptional: true },
        { name: 'timesheet_series_per_device', type: 'boolean', isOptional: true },
        { name: 'timesheet_series_device_code', type: 'string', isOptional: true },
        { name: 'app_lock_enabled', type: 'boolean', isOptional: true },
        { name: 'app_lock_biometric_enabled', type: 'boolean', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'config_storage',
      columns: [
        { name: 'config_key', type: 'string', isIndexed: true },
        { name: 'config_value', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'currency_setting',
      columns: [
        { name: 'code', type: 'string', isIndexed: true },
        { name: 'prefix', type: 'string', isOptional: true },
        { name: 'suffix', type: 'string', isOptional: true },
        { name: 'sort_order', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'client',
      columns: [
        { name: 'name', type: 'string', isOptional: true },
        { name: 'vat_number', type: 'string', isOptional: true },
        { name: 'company_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'is_company', type: 'boolean' },
        { name: 'is_vat_payer', type: 'boolean' },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'export_language', type: 'string', isOptional: true },
        { name: 'invoice_qr_type', type: 'string', isOptional: true },
        { name: 'invoice_default_export_format', type: 'string', isOptional: true },
        { name: 'invoice_payment_method', type: 'string', isOptional: true },
        { name: 'invoice_due_days', type: 'number', isOptional: true },
        { name: 'billing_interval_enabled', type: 'boolean' },
        { name: 'billing_interval_minutes', type: 'number', isOptional: true },
        { name: 'timer_limit_mode', type: 'string', isOptional: true },
        { name: 'timer_soft_limit_minutes', type: 'number', isOptional: true },
        { name: 'timer_hard_limit_minutes', type: 'number', isOptional: true },
        { name: 'is_archived', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'client_address',
      columns: [
        { name: 'client_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' }, // AddressType enum: 'billing', 'shipping', 'other'
        { name: 'street', type: 'string' },
        { name: 'street2', type: 'string', isOptional: true },
        { name: 'city', type: 'string' },
        { name: 'postal_code', type: 'string' },
        { name: 'country', type: 'string' },
        { name: 'is_default', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'time_entry',
      columns: [
        { name: 'client_id', type: 'string', isIndexed: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'start_time', type: 'number' },
        { name: 'end_time', type: 'number', isOptional: true },
        { name: 'duration', type: 'number', isOptional: true }, // in seconds
        { name: 'is_running', type: 'boolean', isIndexed: true },
        { name: 'is_paused', type: 'boolean', isIndexed: true },
        { name: 'paused_at', type: 'number', isOptional: true },
        { name: 'total_paused_duration', type: 'number', isOptional: true }, // in seconds
        { name: 'running_device_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'running_device_name', type: 'string', isOptional: true },
        { name: 'timesheet_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'timesheet_duration', type: 'number', isOptional: true }, // frozen rounded seconds at timesheet generation
        { name: 'price_list_item_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'rate', type: 'number', isOptional: true },
        { name: 'rate_currency', type: 'string', isOptional: true },
        { name: 'timer_soft_limit_minutes', type: 'number', isOptional: true },
        { name: 'timer_hard_limit_minutes', type: 'number', isOptional: true },
        { name: 'soft_limit_notified_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'price_list_item',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'default_price', type: 'number' },
        { name: 'default_price_currency', type: 'string', isOptional: true },
        { name: 'unit', type: 'string' },
        { name: 'vat_code_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'vat_name', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'client_price_override',
      columns: [
        { name: 'client_id', type: 'string', isIndexed: true },
        { name: 'price_list_item_id', type: 'string', isIndexed: true },
        { name: 'custom_price', type: 'number' },
        { name: 'custom_price_currency', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_operation',
      columns: [
        { name: 'op_id', type: 'string', isIndexed: true },
        { name: 'table_name', type: 'string', isIndexed: true },
        { name: 'record_id', type: 'string', isIndexed: true },
        { name: 'operation_type', type: 'string' }, // insert/update/delete
        { name: 'payload_json', type: 'string', isOptional: true },
        { name: 'base_version', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'retry_count', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sync_conflict',
      columns: [
        { name: 'table_name', type: 'string', isIndexed: true },
        { name: 'record_id', type: 'string', isIndexed: true },
        { name: 'conflict_type', type: 'string' }, // update/update, delete/update, etc.
        { name: 'base_payload_json', type: 'string', isOptional: true },
        { name: 'local_payload_json', type: 'string', isOptional: true },
        { name: 'remote_payload_json', type: 'string', isOptional: true },
        { name: 'conflicting_fields_json', type: 'string', isOptional: true },
        { name: 'resolution_json', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true }, // pending/resolved/applied
        { name: 'resolved_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'vat_code',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'country_code', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'vat_rate',
      columns: [
        { name: 'vat_code_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'rate_percent', type: 'number' },
        { name: 'valid_from', type: 'number', isIndexed: true },
        { name: 'valid_to', type: 'number', isOptional: true, isIndexed: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'timesheet',
      columns: [
        { name: 'client_id', type: 'string', isIndexed: true },
        { name: 'period_type', type: 'string' },
        { name: 'period_from', type: 'number', isIndexed: true },
        { name: 'period_to', type: 'number', isIndexed: true },
        { name: 'timesheet_number', type: 'string', isOptional: true, isIndexed: true },
        { name: 'label', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'invoice',
      columns: [
        { name: 'client_id', type: 'string', isIndexed: true },
        { name: 'invoice_number', type: 'string', isIndexed: true },
        { name: 'issued_at', type: 'number', isIndexed: true },
        { name: 'taxable_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'due_at', type: 'number', isOptional: true },
        { name: 'currency', type: 'string' },
        { name: 'payment_method', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'header_note', type: 'string', isOptional: true },
        { name: 'footer_note', type: 'string', isOptional: true },
        { name: 'seller_snapshot_json', type: 'string', isOptional: true },
        { name: 'buyer_snapshot_json', type: 'string', isOptional: true },
        { name: 'last_exported_at', type: 'number', isOptional: true, isIndexed: true },
        { name: 'corrected_invoice_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'correction_kind', type: 'string', isOptional: true },
        { name: 'cancellation_reason', type: 'string', isOptional: true },
        { name: 'subtotal', type: 'number' },
        { name: 'total', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'invoice_item',
      columns: [
        { name: 'invoice_id', type: 'string', isIndexed: true },
        { name: 'source_kind', type: 'string' }, // timesheet | price_list | manual
        { name: 'source_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'description', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit', type: 'string', isOptional: true },
        { name: 'unit_price', type: 'number' },
        { name: 'total_price', type: 'number' },
        { name: 'vat_code_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'vat_rate', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
